export enum ACCION_CONTRATO {
    ACCION_CREADO = 'CREADO',
    ACCION_MODIFICADO = 'MODIFICADO',
    ACCION_RENOVADO = 'RENOVADO',
    ACCION_TERMINADO = 'TERMINADO',
    ACCION_SUSPENDIDO = 'SUSPENDIDO'
}

export enum ESTADO_CONTRATO {
    ESTADO_VIGENTE = 'VIGENTE',
    ESTADO_VENCIDO = 'VENCIDO',
    ESTADO_SUSPENDIDO = 'SUSPENDIDO',
    ESTADO_TERMINADO = 'TERMINADO'
}